### ISSUE TITLE
EPIC: Maps

### ISSUE THREAD

**Issue by mrhegemon** [EtherealEngine/ee-maps#4]
Will probably need a map API key and much work.

Help plan refactor and document state of features.

- [ ] https://github.com/EtherealEngine/ee-maps/issues/5
- [ ] https://github.com/EtherealEngine/ee-maps/issues/6
- [ ] https://github.com/EtherealEngine/ee-maps/issues/7
- [ ] https://github.com/EtherealEngine/ee-maps/issues/8

**Comment by mrhegemon** [comment]
Yes, please go forward on these fronts

1 create documentation for the current version breaking down the major systems

2 update the current system for v1.1 of Ethereal Engine

3. Explore streaming Maps/Textures/geometry out of CesiumJS into Ethereal Engine
